spring:
  datasource:
    url: jdbc:postgresql://192.168.68.61:5433/bytetech-invoice
    username: citizix_user
    password: S3cret
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    hibernate:
      ddl-auto: update   # <-- let Hibernate auto-create/update tables
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080