# .github/workflows/build-and-push.yml
name: Build & Push Image (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/invoice-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 👇 Retry build+push up to 3 times on failures like 502
      - name: Build & Push (retry)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 20
          retry_on: error
          command: |
            docker buildx build \
              --push \
              --file ./Dockerfile \
              --tag "${{ env.IMAGE_NAME }}:latest" \
              --tag "${{ env.IMAGE_NAME }}:${{ github.sha }}" \
              --cache-from=type=gha \
              --cache-to=type=gha,mode=max \
              .