name: Build & Push Image (GHCR)

on:
  push:
    branches: [ main ]   # adjust if needed
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/invoice-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read         # checkout
      packages: write        # push to GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max